STORE_PATH = "trading/store/"
CSV_PATH = STORE_PATH + "csv/"
ACCESS_TOKEN_DB_PATH = STORE_PATH + "db/auth/auth.db"
BACK_TEST_OHLC_DB_PATH = STORE_PATH + "db/stock_data/ohlc.db"
TICKS_DB_PATH = STORE_PATH + "db/stock_data/ticks.db"
SCREENER_DB_PATH = STORE_PATH + "db/screener/screener.db"
STRATEGY_DB_PATH = STORE_PATH + "db/strategies/"
EXCHANGE = "NSE"
SUPER_TREND_STRATEGY_7_3 = "SuperTrendStrategy73"
PARABOLIC_SAR = "ParabolicSAR"
PARABOLIC_SAR_MTF = "ParabolicSARMultiTimeFrame"
ADAPTIVE_SAR_STRATEGY = "AdaptiveSAR"
ADX_STRATEGY = "ADXStrategy"
SPM_STRATEGY = "SPMStrategy"

# Mode constants
BACK_TEST = "backtest"
SETUP = "setup"
SCREEN = "screen"
LIVE = "live"
