STORE_PATH = "trading/store/"
TICKS_DB_PATH = STORE_PATH + "ticks.db"
SCREENER_DB_PATH = STORE_PATH + "screener.db"
STRATEGY_DB_PATH = STORE_PATH + "db/strategies/"
EXCHANGE = "NSE"
SUPER_TREND_STRATEGY_7_3 = "SuperTrendStrategy73"
PARABOLIC_SAR = "ParabolicSAR"
